### ISSUE TITLE
make cross-all all failed

### ISSUE THREAD

**Issue by 64BitAsura** [anshulrouthu/RPiCast#2]
# make cross-all all

Package libavdevice was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavdevice.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavdevice' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing`libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing`libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libswresample was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswresample.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswresample' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing`libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
make[1]: Entering directory '/home/RPiCast'
[CXX] source/porting_layers/components/video_capture.o
make[1]: ./rpi-toolchain/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++: Command not found
Makefile.cross:98: recipe for target 'source/porting_layers/components/video_capture.o' failed
make[1]: **\* [source/porting_layers/components/video_capture.o] Error 127
make[1]: Leaving directory '/home/RPiCast'
Makefile:166: recipe for target 'cross-all' failed
make: **\* [cross-all] Error 2

**Comment by anshulrouthu** [comment]
Try running the setup.sh. That script will install all the required libraries and toolchain in your sand box

**Comment by anshulrouthu** [comment]
If you got this working can this issue be closed ?

**Comment by 64BitAsura** [comment]
I couldn't get it working in ubuntu 12 on virtual box :(

**Comment by anshulrouthu** [comment]
fixed with the latest commit on master
