### ISSUE TITLE
error : make cross-all all

### ISSUE THREAD

**Issue by ghost** [anshulrouthu/RPiCast#4]
hi from france,
` uname -a
Linux VAIO 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`
can you explain me :

` make cross-all all
Package libavdevice was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavdevice.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavdevice' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libswresample was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswresample.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswresample' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
make[1] : on entre dans le répertoire « /home/celtiore/Vidéos/RPiCast-master »
#@scp -r rpi-build/* root@192.168.1.2:workspace/
make[1] : on quitte le répertoire « /home/celtiore/Vidéos/RPiCast-master »
[CXX] /home/celtiore/Vidéos/RPiCast-master/build/native/source/porting_layers/components/video_capture.o
In file included from /home/celtiore/Vidéos/RPiCast-master/source/porting_layers/components/video_capture.cpp:24:0:
/home/celtiore/Vidéos/RPiCast-master/source/porting_layers/components/video_capture.h:40:10: fatal error: libavcodec/avcodec.h: Aucun fichier ou dossier de ce type
 #include <libavcodec/avcodec.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:97 : la recette pour la cible « /home/celtiore/Vidéos/RPiCast-master/build/native/source/porting_layers/components/video_capture.o » a échouée
make: *** [/home/celtiore/Vidéos/RPiCast-master/build/native/source/porting_layers/components/video_capture.o] Erreur 1
`

thanks you

**Comment by ghost** [comment]
fixed :  sudo apt install libavdevice-dev

**Comment by anshulrouthu** [comment]
In order to prevent this kind of system dependency on libav* libraries, setup.sh will build the ffmpeg library locally from with in the repository and installs in (root)/staging directory. If you had successfully run the setup.sh script you wouldn't need to install the libavdevice-dev on your system. I will fix the setup.sh script to error out if the setup was not successful, that was bad on my part.
